### ISSUE TITLE
Need more Documentation!

### ISSUE THREAD

**Issue by slarrain** [pawel-jakubowski/kanban#1]
The projects sounds awesome, but I think it needs more documentation. How should I use it? Install it?

**Comment by pawel-jakubowski** [comment]
Thank you for taking interest in my project :)
I have added README, but please remember that this software is still in it's early stage. A lot of work has to be done before achieving version 1.0

**Comment by slarrain** [comment]
No problem. I hope to know enough GTK one day to be able to contribute. 
Thanks!
